#twig:
#    default_path: '%kernel.project_dir%/templates'

twig:
    globals:
        supported_locales: '%app.supported_locales%'

when@test:
    twig:
        strict_variables: true
        globals:
            supported_locales: '%app.supported_locales%'

